name: Build EXE WinOS

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
  release:
    types:
      - created


jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install package
        run: pip install .

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile stock_management/main.py

      - name: List directory contents
        run: ls -R

      - name: Archive EXE
        run: Compress-Archive -Path $PWD\dist -DestinationPath stock_management.zip

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: stock_management
          path: stock_management.zip

      - name: Publish artifact
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ${{ github.workspace }}\stock_management.zip
          asset_name: stock_management.zip
          release_id: ${{ github.event.inputs.release_version }}