name: Functional tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  functional_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Checkout folder project
      uses: actions/checkout@v2

    - name: Install package
      run: pip install .

    - name: Install xvfb
      run: sudo apt-get install xvfb -y

    - name: Run tests with xvfb
      run: xvfb-run pytest